### ISSUE TITLE
Not working with Angular 2 version 2.4.6

### ISSUE THREAD

**Issue by PrasanthJayaraman** [drozhzhin-n-e/ng2-tooltip-directive#22]
I get the renderer2 issue, looks like you forgot about the backward compatability, Angualr2 has Renderer and Angular4 has Renderer2.

`ERROR: node_modules/ng2-tooltip-directive/lib/tooltip.component.d.ts(1,36): Error TS2305: Module '"node_modules/@angular/core/index"' has no exported member 'Renderer2'.`
